// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview and Concept',
      items: ['overview and concept/overview',
              'overview and concept/concept',
              'overview and concept/target audience',],
        
    },
    {
      type: 'category',
      label: 'Project Workflow',
      items: ['workflow/workflow'],
    },
    {
      type: 'category',
      label: 'Installation and Setup',
      items: ['installation/Install Ubuntu',
              'installation/Install Docker',
              'installation/IDE Setup',
              'installation/Install ROS',
              'installation/setup',],
    },
    {
      type: 'category',
      label: 'Hardware',
      items: ['hardware/hardware-setup'],
    },
    {
      type: 'category',
      label: 'Tutorials and Resources',
      items: ['tutorials/getting-started',
              'tutorials/start simulation',
              'tutorials/build ROS nodes',
              'tutorials/controller node',
              'tutorials/planner node',
              'tutorials/transition to hardware'
              ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: ['troubleshooting/common-issues'],
    },
  ],
};

export default sidebars;
